/// Wraps the body of a method so its work is executed as a system-managed
/// background task.
///
/// This macro automatically injects calls to
/// `UIApplication.shared.beginBackgroundTask(_:)` and
/// `UIApplication.shared.endBackgroundTask(_:)`, ensuring that background
/// execution is started and ended safely around the method’s body.
///
/// - Parameters:
///   - propertyName:
///     The name of the stored property (e.g., `_backgroundTaskID`) that holds the
///     `UIBackgroundTaskIdentifier`. This property must be accessible on `self`
///     and is typically generated by the `@BackgroundableProperty` macro.
///     If `nil`, the macro generates a local variable within the function
///     (e.g., `var backgroundTaskID`) and uses that instance instead.
///   - withName:
///     A descriptive, human-readable name for the background task, useful for
///     debugging in Xcode or Instruments.
///   - expirationFunc:
///     The name of a function to invoke *inside the expiration handler* passed
///     to `UIApplication.beginBackgroundTask(_:)`. This function is called when
///     the system notifies the app that the task is about to expire, providing a
///     location for cleanup or fallback logic.
///
@available(iOS 13, tvOS 13, macCatalyst 13, visionOS 1, *)
@attached(body)
public macro Backgroundable(propertyName: String? = nil, withName: String? = nil, expirationFunc: String? = nil) = #externalMacro(module: "BackgroundableMacros", type: "BackgroundableMacro")

/// Injects a stored property for holding a background task identifier.
///
/// This macro adds a stored property to the surrounding type (typically a class),
/// intended to safely store the `UIBackgroundTaskIdentifier` used by the
/// `@Backgroundable` macro.
///
/// - Parameters:
///   - name:
///     The name of the generated property. If omitted, a default name
///     (e.g., `_backgroundTaskID`) will be generated by the macro.
///
@available(iOS 13, tvOS 13, macCatalyst 13, visionOS 1, *)
@attached(member, names: arbitrary)
public macro BackgroundableProperty(name: String? = nil) = #externalMacro(module: "BackgroundableMacros", type: "BackgroundablePropertyMacro")

